// Cook Mode's measurements (spec §4.20, v1 CookModeModal.tsx), kept exact so the
// screen reads the same at arm's length as the original did.

export const COOK = {
  /** Header row: close button, centred title, ingredients button, step counter. */
  headerX: 16,
  headerTop: 4,
  headerBottom: 8,
  headerGap: 12,
  closeButton: 38,
  closeIcon: 22,
  listButton: 36,
  listIcon: 18,
  /** The meal name stays one line and never crowds the buttons. */
  titleMaxWidth: 220,
  titleTop: 2,
  counterMinWidth: 38,
  /** The progress strip: one segment per step, shared out past twelve so none shrink to slivers. */
  progressX: 20,
  progressTop: 14,
  progressBottom: 4,
  progressGap: 4,
  progressHeight: 3,
  progressMaxSegments: 12,
  /** The step body. */
  bodyTop: 18,
  bodyBottom: 36,
  numeralBottom: 8,
  kickerBottom: 22,
  hintTop: 12,
  /** The footer: "Previous" as text, "Next step" as a black pill. */
  footerX: 16,
  footerTop: 12,
  footerBottom: 8,
  footerGap: 12,
  previousX: 12,
  previousY: 14,
  previousGap: 4,
  nextX: 20,
  nextY: 16,
  nextGap: 8,
  chevron: 18,
  /** The ingredients sheet. */
  sheetHandleWidth: 40,
  sheetHandleHeight: 4,
  sheetHandleBottom: 14,
  sheetHeadX: 20,
  sheetHeadBottom: 14,
  sheetKickerBottom: 6,
  sheetListMax: 480,
  sheetListTop: 12,
  sheetListBottom: 6,
  sheetGroupY: 8,
  sheetSectionBottom: 8,
  sheetRowGap: 10,
  sheetRowY: 5,
  dot: 5,
  /** Centres the dot on the first line of a 14/20 ingredient. */
  dotTop: 8,
  tipBottom: 4,
  haveGap: 3,
  havePadLeft: 5,
  havePadRight: 7,
  havePadY: 3,
  haveIcon: 10,
  tipIcon: 12,
  sheetDoneX: 16,
  sheetDoneTop: 12,
  sheetDoneY: 14,
} as const;
